In [1]:
import tensorflow as tf
print(tf.__version__)

2.16.2


In [15]:
x = tf.Variable([[1, 1, 0],
                 [0, 0, 1],
                 [0, 0, 1]])

print(x)

y = tf.Variable([[1, 0, 0], 
                 [0, 1, 0],
                 [0, 0, 1]])

print(y)

z = tf.matmul(x, y)
print(z)

w = tf.matmul(x, z)
print(w)
v = x @ x
print(v)

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[1, 1, 0],
       [0, 0, 1],
       [0, 0, 1]])>
<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])>
tf.Tensor(
[[1 1 0]
 [0 0 1]
 [0 0 1]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[1 1 1]
 [0 0 1]
 [0 0 1]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[1 1 1]
 [0 0 1]
 [0 0 1]], shape=(3, 3), dtype=int32)
