In [4]:
import tensorflow as tf
import numpy as np

input = np.arange(10)
print(input)
print(input.shape)

input = tf.expand_dims(input, 0)
print(input)
print(input.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)
tf.Tensor([[0 1 2 3 4 5 6 7 8 9]], shape=(1, 10), dtype=int32)
(1, 10)


In [5]:
input = tf.squeeze(input, 0)
print(input)
print(input.shape)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
(10,)
