In [4]:
import numpy as np

data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [6]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
arr2.ndim

2

In [12]:
arr2.shape

(2, 4)

In [16]:
arr1.dtype

dtype('float64')

In [18]:
arr2.dtype

dtype('int32')

In [20]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [24]:
np.empty((2, 3, 2))

array([[[1.01855798e-312, 1.10343781e-312],
        [1.01855798e-312, 9.54898106e-313],
        [1.20953760e-312, 1.01855798e-312]],

       [[1.23075756e-312, 1.16709769e-312],
        [1.01855798e-312, 9.76118064e-313],
        [1.14587773e-312, 1.90979621e-312]]])

In [26]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])