In [2]:
import numpy as np

x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [3]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [4]:
x.shape

(2, 3)

In [5]:
y.shape

(3, 2)

In [6]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [7]:
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [8]:
np.ones(3)

array([1., 1., 1.])

In [9]:
x @ np.ones(3)

array([ 6., 15.])

In [10]:
from numpy.linalg import inv, qr
X = np.random.standard_normal((5, 5))

In [11]:
mat = X.T.dot(X) # mat = X.T @ X
#mat

In [12]:
inv(mat)

array([[ 0.73849331,  3.02166525,  3.29524085,  0.65633989,  0.466189  ],
       [ 3.02166525, 14.35264591, 15.7331953 ,  3.143609  ,  2.07606602],
       [ 3.29524085, 15.7331953 , 17.6569923 ,  3.34925105,  2.24586592],
       [ 0.65633989,  3.143609  ,  3.34925105,  0.93224102,  0.51525165],
       [ 0.466189  ,  2.07606602,  2.24586592,  0.51525165,  0.42195443]])

In [13]:
mat @ inv(mat)

array([[ 1.00000000e+00,  3.90743246e-16,  1.95985744e-15,
         1.19700602e-15, -1.02107403e-16],
       [ 1.09062093e-15,  1.00000000e+00, -1.33601476e-14,
        -2.03296222e-16,  2.06454705e-17],
       [-1.16196240e-15, -4.74822941e-15,  1.00000000e+00,
         6.51955513e-16,  2.96121127e-16],
       [ 2.79927016e-16, -1.19156081e-16,  5.44952179e-15,
         1.00000000e+00,  8.80020118e-16],
       [-5.17727796e-16, -1.19632406e-15,  1.97747665e-15,
         1.44368954e-16,  1.00000000e+00]])

In [14]:
arr = np.array([[2,4,6],[2,0,2],[6,8,14]])
arr

array([[ 2,  4,  6],
       [ 2,  0,  2],
       [ 6,  8, 14]])

In [16]:
inv(arr)

array([[ 1.35107989e+16,  6.75539944e+15, -6.75539944e+15],
       [ 1.35107989e+16,  6.75539944e+15, -6.75539944e+15],
       [-1.35107989e+16, -6.75539944e+15,  6.75539944e+15]])

In [18]:
arr @ inv(arr)

array([[ 8., -2., -4.],
       [ 4.,  4., -2.],
       [ 8.,  6., -4.]])

In [31]:
from numpy.linalg import inv, qr
from random import normalvariate

rng = np.random.default_rng()
X = rng.standard_normal((5, 5))
mat = X.T @ X
mat @ inv(mat)

array([[ 1.00000000e+00,  6.29272340e-16,  2.37550668e-16,
         1.53981014e-15,  5.43097321e-16],
       [ 4.54611148e-17,  1.00000000e+00, -1.79467097e-16,
         1.27556468e-17, -2.89964789e-16],
       [ 2.07381499e-16,  2.20371225e-16,  1.00000000e+00,
        -1.01683491e-16,  1.91458609e-16],
       [ 1.29088012e-16,  2.45976428e-16, -6.77438243e-17,
         1.00000000e+00, -7.12022926e-17],
       [-4.03767888e-16, -1.93855268e-16,  4.39202404e-17,
         9.83949707e-16,  1.00000000e+00]])