In [1]:
import numpy as np

x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [2]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [3]:
x.shape

(2, 3)

In [4]:
y.shape

(3, 2)

In [5]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [6]:
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [7]:
np.ones(3)

array([1., 1., 1.])

In [8]:
x @ np.ones(3)

array([ 6., 15.])

In [17]:
from numpy.linalg import inv, qr
X = np.random.standard_normal((5, 5))

In [22]:
mat = X.T.dot(X) # mat = X.T @ X
#mat

In [19]:
inv(mat)

array([[ 1.68872524,  0.96199656, -3.21630274,  0.32226387, -0.20245479],
       [ 0.96199656,  1.4388891 , -2.21991681,  0.13506783,  0.72169174],
       [-3.21630274, -2.21991681, 15.0650806 , -0.74213665,  3.33991754],
       [ 0.32226387,  0.13506783, -0.74213665,  0.13943241, -0.14808383],
       [-0.20245479,  0.72169174,  3.33991754, -0.14808383,  2.2243934 ]])

In [24]:
mat @ inv(mat)

array([[ 1.00000000e+00,  5.56321446e-16, -2.36456056e-16,
        -1.08962904e-16,  4.62144121e-17],
       [-2.13288960e-16,  1.00000000e+00,  1.52636687e-15,
         4.57650275e-17, -2.23913249e-15],
       [-2.70489663e-16, -7.20838703e-16,  1.00000000e+00,
        -1.07467843e-16,  7.40530260e-17],
       [-3.19782384e-16, -2.27718707e-16,  8.68640106e-17,
         1.00000000e+00, -3.61999688e-17],
       [-3.33344012e-16,  2.04134641e-16, -4.05638258e-16,
        -3.97601191e-17,  1.00000000e+00]])

In [36]:
arr = np.array([[2,4,6],[2,0,2],[6,8,14]])
arr

array([[ 2,  4,  6],
       [ 2,  0,  2],
       [ 6,  8, 14]])

In [38]:
inv(arr).astype(int)

C:\Users\shkwon\AppData\Local\Temp\ipykernel_24936\2974657486.py:1: RuntimeWarning: invalid value encountered in cast
  inv(arr).astype(int)


array([[-2147483648, -2147483648, -2147483648],
       [-2147483648, -2147483648, -2147483648],
       [-2147483648, -2147483648, -2147483648]])

In [35]:
arr @ inv(arr)

array([[ 8., -2., -4.],
       [ 4.,  4., -2.],
       [ 8.,  6., -4.]])